set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'

unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

unbind C-b
set -g prefix `
bind ` send-prefix

set -g mouse on

is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"

bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R

# Split horizontal + demande nom
bind v split-window -h \; command-prompt -p "Nom du pane:" "select-pane -T '%%'"

# Split vertical + demande nom
bind h split-window -v \; command-prompt -p "Nom du pane:" "select-pane -T '%%'"

# Nouvelle window + demande nom
bind c new-window \; command-prompt -p "Nom du pane:" "select-pane -T '%%'"

bind [ switch-client -p   # session précédente
bind ] switch-client -n   # session suivante

bind u command-prompt -p "Nom du pane:" "select-pane -T '%%'"

# Kill session shortcut (with cleanup of docker/pnpm processes)
bind X confirm-before -p 'Kill session #S and all processes? (y/n)' 'run-shell ~/.local/bin/tmux-kill-session-clean'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.tmux/plugins/tpm/tpm'
# run '~/.config/tmux/plugins/tmux-cpu/cpu.tmux'

source-file ~/.config/tmux/themes/zen.conf
